/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Initialization File                                              */
/*                                                                  */
/* Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor    */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : cri_Initialize.c                          */
/* Time                 : Sat Jun 27 15:04:48 2026                  */
/* Working directory    : /lfs1i3/projects/public/b35as/HAPCEMM-Chem/kpp_cri */
/* Equation file        : cri.kpp                                   */
/* Output root filename : cri                                       */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "cri_Parameters.h"
#include "cri_Global.h"
#include "cri_Sparse.h"


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Initialize - function to initialize concentrations               */
/*   Arguments :                                                    */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Initialize( 
)
{
int i;                                  
double x;                               

  CFACTOR = 1.000000e+00;

  x = (0.)*CFACTOR;
  for( i = 0; i < NVAR; i++ )
    VAR[i] = x;

  x = (0.)*CFACTOR;
  for( i = 0; i < NFIX; i++ )
    FIX[i] = x;

/* constant rate coefficients                                       */
  RCONST[11] = 1.29e-11;
  RCONST[12] = 1.39e-11;
  RCONST[14] = 3.7e-12;
  RCONST[16] = 5.3e-12;
  RCONST[17] = 5.4e-12;
  RCONST[21] = 6.86e-12;
  RCONST[29] = 3.7e-11;
  RCONST[32] = 6.54e-11;
  RCONST[33] = 6.69e-11;
  RCONST[34] = 6e-11;
  RCONST[35] = 6e-11;
  RCONST[37] = 6.07e-11;
  RCONST[43] = 1.2e-14;
  RCONST[44] = 1.2e-14;
  RCONST[45] = 3.5e-13;
  RCONST[46] = 3.9e-13;
  RCONST[47] = 3.7e-13;
  RCONST[48] = 3.7e-13;
  RCONST[49] = 3.7e-13;
  RCONST[50] = 3.7e-13;
  RCONST[51] = 3.4e-13;
  RCONST[52] = 3.3e-13;
  RCONST[53] = 1.2e-14;
  RCONST[54] = 9.37e-12;
  RCONST[89] = 1.03e-13;
  RCONST[101] = 2.51e-12;
  RCONST[124] = 5.67e-11;
  RCONST[125] = 1.19e-11;
  RCONST[126] = 1.86e-11;
  RCONST[127] = 1.18e-11;
  RCONST[132] = 5.67e-11;
  RCONST[133] = 5.67e-11;
  RCONST[134] = 5.8e-11;
  RCONST[135] = 1.5e-12;
  RCONST[139] = 2.4e-15;
  RCONST[154] = 5.5e-16;
  RCONST[173] = 4.9e-12;
  RCONST[174] = 2.77e-12;
  RCONST[175] = 2e-12;
  RCONST[176] = 9.1e-12;
  RCONST[177] = 6.9e-12;
  RCONST[178] = 1.41e-11;
  RCONST[179] = 1.21e-12;
  RCONST[180] = 5.4e-12;
  RCONST[196] = 1.12e-11;
  RCONST[197] = 1.31e-11;
  RCONST[198] = 3.85e-12;
  RCONST[205] = 1.45e-11;
  RCONST[217] = 1.8e-11;
  RCONST[218] = 1.59e-11;
  RCONST[219] = 2.31e-11;
  RCONST[220] = 2.78e-11;
  RCONST[221] = 2.6e-16;
  RCONST[222] = 2.8e-15;
  RCONST[223] = 6.5e-15;
  RCONST[224] = 6.4e-16;
  RCONST[225] = 1.91e-15;
  RCONST[226] = 1.53e-15;
  RCONST[227] = 2.8e-15;
  RCONST[228] = 3.76e-15;
  RCONST[229] = 4.65e-15;
  RCONST[230] = 6.5e-15;
  RCONST[231] = 4.93e-12;
  RCONST[232] = 3.2e-13;
  RCONST[233] = 4.5e-13;
  RCONST[234] = 8e-13;
  RCONST[235] = 1.2e-12;
  RCONST[425] = 1.2e-12;
  RCONST[817] = 2.06e-11;
  RCONST[818] = 1.87e-11;
  RCONST[819] = 4.36e-12;
  RCONST[820] = 7.89e-12;
  RCONST[821] = 1.13e-11;
  RCONST[822] = 1.27e-11;
  RCONST[823] = 1.42e-11;
  RCONST[824] = 1.56e-11;
  RCONST[825] = 1.7e-11;
  RCONST[827] = 1.83e-11;
  RCONST[829] = 5.86e-12;
  RCONST[830] = 1.65e-11;
  RCONST[831] = 1.25e-11;
  RCONST[832] = 8.07e-12;
  RCONST[833] = 7.98e-12;
  RCONST[834] = 6.4e-12;
  RCONST[835] = 6.47e-12;
  RCONST[836] = 9.47e-12;
  RCONST[837] = 8.86e-12;
  RCONST[842] = 1e-11;
  RCONST[846] = 2.4e-13;
  RCONST[847] = 1.38e-12;
  RCONST[848] = 4.81e-12;
  RCONST[849] = 6.3e-12;
  RCONST[850] = 7.8e-12;
  RCONST[851] = 9.3e-12;
  RCONST[852] = 1.08e-11;
  RCONST[853] = 1.23e-11;
  RCONST[854] = 1.38e-11;
  RCONST[855] = 4.79e-12;
  RCONST[856] = 6.42e-11;
  RCONST[860] = 4.16e-11;
  RCONST[861] = 6.7e-13;
  RCONST[872] = 9.36e-13;
  RCONST[873] = 7.42e-13;
  RCONST[874] = 4.2e-11;
  RCONST[875] = 1e-12;
  RCONST[876] = 1e-10;
  RCONST[877] = 3.8e-14;
  RCONST[879] = 6.65e-12;
  RCONST[880] = 1.55e-11;
  RCONST[881] = 4.55e-12;
  RCONST[882] = 1.5e-12;
  RCONST[912] = 7.3e-13;
  RCONST[913] = 4.9e-13;
  RCONST[914] = 9.2e-13;
  RCONST[915] = 1.85e-12;
  RCONST[916] = 3.02e-12;
  RCONST[917] = 3.69e-12;
  RCONST[918] = 3.88e-12;
  RCONST[919] = 6.76e-12;
  RCONST[920] = 8.15e-12;
  RCONST[921] = 9.54e-12;
  RCONST[922] = 1.09e-11;
  RCONST[923] = 2.23e-13;
  RCONST[924] = 9.67e-13;
  RCONST[925] = 3.3e-12;
  RCONST[926] = 1.09e-12;
  RCONST[927] = 1.31e-12;
  RCONST[928] = 1.79e-12;
  RCONST[929] = 1.03e-11;
  RCONST[930] = 1.34e-11;
  RCONST[931] = 1.23e-11;
  RCONST[932] = 1.38e-11;
  RCONST[933] = 1.48e-11;
  RCONST[934] = 1.58e-11;
  RCONST[935] = 1.68e-11;
  RCONST[936] = 1.78e-11;
  RCONST[937] = 8.48e-13;
  RCONST[938] = 1.32e-12;
  RCONST[939] = 4.21e-11;
  RCONST[941] = 7.3e-11;
  RCONST[942] = 7.16e-11;
  RCONST[943] = 8.31e-11;
  RCONST[944] = 9.45e-11;
  RCONST[945] = 9.57e-11;
  RCONST[946] = 9.67e-11;
  RCONST[947] = 7.74e-12;
  RCONST[948] = 1.48e-12;
  RCONST[949] = 6e-13;
  RCONST[950] = 4.35e-12;
  RCONST[951] = 2.88e-12;
  RCONST[952] = 3.53e-12;
  RCONST[953] = 6.48e-12;
  RCONST[954] = 4.74e-12;
  RCONST[955] = 2.63e-11;
  RCONST[956] = 3.78e-12;
  RCONST[957] = 2.08e-12;
  RCONST[958] = 9e-13;
  RCONST[959] = 9e-14;
  RCONST[960] = 4.65e-11;
  RCONST[961] = 1.25e-11;
  RCONST[962] = 2.08e-12;
  RCONST[963] = 1.53e-12;
  RCONST[964] = 3.13e-13;
  RCONST[1045] = 1.36e-11;
  RCONST[1046] = 1.89e-11;
  RCONST[1047] = 2.78e-11;
  RCONST[1048] = 3.57e-11;
  RCONST[1049] = 4.21e-11;
  RCONST[1050] = 4.71e-11;
  RCONST[1051] = 4.85e-11;
  RCONST[1052] = 4.99e-11;
  RCONST[1053] = 5.13e-11;
  RCONST[1054] = 5.27e-11;
  RCONST[1055] = 5.41e-11;
  RCONST[1056] = 5.55e-11;
  RCONST[1057] = 5.82e-12;
  RCONST[1058] = 1.23e-11;
  RCONST[1059] = 3.7e-12;
  RCONST[1060] = 4.42e-12;
  RCONST[1061] = 6.19e-12;
  RCONST[1062] = 1.2e-11;
  RCONST[1063] = 2.5e-11;
  RCONST[1064] = 3.2e-11;
  RCONST[1065] = 3.35e-11;
  RCONST[1066] = 3.5e-11;
  RCONST[1067] = 3.65e-11;
  RCONST[1068] = 3.8e-11;
  RCONST[1069] = 3.95e-11;
  RCONST[1070] = 4.1e-11;
  RCONST[1071] = 4.25e-11;
  RCONST[1072] = 6.26e-12;
  RCONST[1073] = 1.58e-11;
  RCONST[1074] = 4.89e-12;
  RCONST[1075] = 7.89e-11;
  RCONST[1077] = 3.5e-11;
  RCONST[1078] = 3.84e-11;
  RCONST[1079] = 1.03e-10;
  RCONST[1080] = 2.65e-11;
  RCONST[1081] = 2.13e-11;
  RCONST[1082] = 2.5e-11;
  RCONST[1083] = 3.25e-11;
  RCONST[1084] = 3.74e-11;
  RCONST[1085] = 3.83e-11;
  RCONST[1086] = 5.25e-11;
  RCONST[1087] = 5.4e-11;
  RCONST[1088] = 5.55e-11;
  RCONST[1089] = 5.7e-11;
  RCONST[1090] = 5.85e-11;
  RCONST[1091] = 6e-11;
  RCONST[1092] = 8.1e-12;
  RCONST[1093] = 1.66e-11;
  RCONST[1094] = 3.53e-11;
  RCONST[1095] = 5.22e-12;
  RCONST[1096] = 6.5e-12;
  RCONST[1097] = 7.15e-12;
  RCONST[1098] = 9.05e-12;
  RCONST[1099] = 1.08e-11;
  RCONST[1100] = 4.18e-12;
  RCONST[1101] = 7e-12;
  RCONST[1102] = 9.77e-11;
  RCONST[1103] = 9.64e-11;
  RCONST[1104] = 1.12e-10;
  RCONST[1105] = 1.28e-10;
  RCONST[1106] = 1.28e-10;
  RCONST[1107] = 1.28e-10;
  RCONST[1108] = 6.16e-11;
  RCONST[1109] = 4.66e-12;
  RCONST[1110] = 6.16e-11;
  RCONST[1111] = 2.38e-11;
  RCONST[1112] = 1.2e-11;
  RCONST[1113] = 9.5e-12;
  RCONST[1114] = 1.66e-11;
  RCONST[1115] = 1.05e-11;
  RCONST[1116] = 2.05e-11;
  RCONST[1117] = 8.69e-11;
  RCONST[1118] = 4.23e-12;
  RCONST[1119] = 2e-11;
  RCONST[1120] = 8.59e-11;
  RCONST[1121] = 7.5e-11;
  RCONST[1122] = 9.58e-12;
  RCONST[1129] = 3e-14;
  RCONST[1130] = 1.27e-12;
  RCONST[1131] = 1.12e-12;
  RCONST[1136] = 3.66e-12;
  RCONST[1152] = 2.5e-12;
  RCONST[1154] = 5.26e-13;
  RCONST[1158] = 1.16e-11;
  RCONST[1185] = 5.2e-11;
  RCONST[1186] = 2.4e-17;
  RCONST[1189] = 5.78e-11;
  RCONST[1190] = 3.64e-11;
  RCONST[1193] = 3.42e-11;
  RCONST[1200] = 5.64e-11;
  RCONST[1235] = 2e-11;
  RCONST[1239] = 4e-12;
  RCONST[1245] = 6e-06;
  RCONST[1246] = 0.0004;
/* END constant rate coefficients                                   */

/* INLINED initializations                                          */

/* End INLINED initializations                                      */

}

/* End of Initialize function                                       */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


