#include "KPP/KPP_Parameters.h"
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Global Data Header File                                          */
/*                                                                  */
/* Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor    */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : cri_Global.h                              */
/* Time                 : Sat Jun 27 15:04:48 2026                  */
/* Working directory    : /lfs1i3/projects/public/b35as/HAPCEMM-Chem/kpp_cri */
/* Equation file        : cri.kpp                                   */
/* Output root filename : cri                                       */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */




/* Declaration of global variables                                  */

extern double C[NSPECALL];                         /* Concentration of all species */
  extern double * VAR;
  extern double * FIX;
extern double RCONST[NREACT];                   /* Rate constants (global) */
extern double TIME;                             /* Current integration time */
extern double SUN;                              /* Sunlight intensity between [0,1] */
extern double TEMP;                             /* Temperature */
extern double RTOLS;                            /* (scalar) Relative tolerance */
extern double TSTART;                           /* Integration start time */
extern double TEND;                             /* Integration end time */
extern double DT;                               /* Integration step */
extern double ATOL[NSPEC];                      /* Absolute tolerance */
extern double RTOL[NSPEC];                      /* Relative tolerance */
extern double STEPMIN;                          /* Lower bound for integration step */
extern double STEPMAX;                          /* Upper bound for integration step */
extern double CFACTOR;                          /* Conversion factor for concentration units */
extern int DDMTYPE;                             /* DDM sensitivity w.r.t.: 0=init.val., 1=params */
extern int LOOKAT[1];                     /* Indexes of species to look at */
extern int MONITOR[1];                   /* Indexes of species to monitor */
extern const char * SPC_NAMES[NSPEC];                 /* Names of chemical species */
extern char * SMASS[NMASS];                     /* Names of atoms for mass balance */
extern const char * EQN_NAMES[NREACT];                /* Equation names */
extern char * EQN_TAGS[NREACT];                 /* Equation tags */

/* INLINED global variable declarations                             */

/* INLINED global variable declarations                             */


/* Declarations of other variables present in KPP_Global.h to satisfy threadprivate pragma */
extern double TIME;
extern double SUN;
extern double TEMP;
extern double RTOLS;
extern double TSTART;
extern double TEND;
extern double DT;
extern double ATOL[NVAR];
extern double RTOL[NVAR];
extern double STEPMIN;
extern double STEPMAX;
extern double CFACTOR;
extern int DDMTYPE;
extern double NOON_JRATES[NPHOTOL];
extern double PHOTOL[NPHOTOL];
extern double HET[NSPEC][3];
extern double SZA_CST[3];

#pragma omp threadprivate( C, VAR, FIX, RCONST, TIME, SUN, TEMP, RTOLS, TSTART, TEND, DT, ATOL, RTOL, STEPMIN, STEPMAX, CFACTOR, DDMTYPE, NOON_JRATES, PHOTOL, HET, SZA_CST )
